version: '2.3'

services:
  simple:
    image: gpuenv:simple
    build:
      context: ../
      dockerfile: docker/Dockerfile
    runtime: nvidia
  pyenv:
    image: gpuenv:pyenv
    build:
      context: ../
      dockerfile: docker/pyenv/Dockerfile
    runtime: nvidia
